import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getSupabaseServerClient } from "@/server/supabase/server-client";
import { getPerson } from "@/server/people/queries";
import { getDraftBatch } from "@/server/messages/queries";
import { readDraftMetadata } from "@/server/messages/mappers";
import { updateMessageDraftContent, recordMessageAction } from "@/server/messages/actions";
import { DraftCard } from "@/components/DraftCard";

export const metadata: Metadata = { title: "Message options" };

export default async function DraftBatchPage({
  params,
}: {
  params: Promise<{ personId: string; batchId: string }>;
}) {
  const { personId, batchId } = await params;
  const supabase = await getSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const person = await getPerson(supabase, personId);
  if (!person) notFound();

  const drafts = (await getDraftBatch(supabase, batchId)).filter(
    (d) => d.personId === personId,
  );
  const [firstDraft] = drafts;
  if (!firstDraft) notFound();

  const metadata = readDraftMetadata(firstDraft);
  const isDemo = metadata?.provider === "demo";
  const occasion = metadata?.generation.occasion ?? "A message for you";

  const boundUpdate = updateMessageDraftContent.bind(null, personId, batchId);
  const boundRecord = recordMessageAction.bind(null, personId, batchId);

  return (
    <div>
      <Link href={`/people/${personId}`} className="text-primary text-sm">
        &larr; Back to {person.firstName}
      </Link>
      <h1 className="text-ink mt-2 text-xl font-semibold">Message options</h1>
      <p className="text-ink-muted mt-1 text-sm">
        Edit any option freely before copying or sending — nothing is sent automatically.
      </p>

      {isDemo ? (
        <p
          role="status"
          className="border-border bg-surface mt-4 rounded-md border border-dashed px-3 py-2 text-xs"
        >
          Generated by the built-in demo generator — no AI provider is configured, so this is not
          live AI output.
        </p>
      ) : null}

      <div className="mt-6 grid gap-4 sm:grid-cols-3">
        {drafts.map((draft) => {
          const optionMetadata = readDraftMetadata(draft);
          return (
            <DraftCard
              key={draft.id}
              draft={{
                id: draft.id,
                label: optionMetadata?.optionLabel ?? "Option",
                content: draft.content ?? "",
                channel: draft.channel,
              }}
              person={{ firstName: person.firstName, phone: person.phone, email: person.email }}
              occasion={occasion}
              updateContent={boundUpdate}
              recordAction={boundRecord}
            />
          );
        })}
      </div>

      <Link
        href={`/people/${personId}/drafts/new?regenerate=${batchId}`}
        className="text-primary mt-6 inline-block text-sm"
      >
        Regenerate with different wording
      </Link>
    </div>
  );
}
